export const brand = {
  name: "Lees Cafe",
  nameKo: "리스카페",
  tagline: "소박한 미국식 식당",
  instagram: "@leesfamouscafe",
  instagramUrl: "https://www.instagram.com/leesfamouscafe/",
  foundedYear: 2020,
  story:
    "2020년 판교 백현동 작은 골목에서 시작한 소박한 미국식 식당입니다. 언제든 와도 동네 사랑방 같은 편안하고 따뜻한 분위기로 사람과 사람을 연결합니다.",
  reviewQuote:
    '"보이는 것보다 양이 엄청나게 많음 — 소식하는 사람 둘이서 가면 두 개는 못 먹을 것 같아요."',
};

export const menus = [
  {
    id: 1,
    name: "홈메이드 클램 차우더",
    nameEn: "Homemade Clam Chowder",
    desc: "뉴잉글랜드 스타일로 매일 직접 끓이는 클래식 차우더. 마늘빵과 함께 나옵니다.",
    price: "₩16,800",
    priceRange: "브런치",
    tag: "Best",
    image: "https://images.unsplash.com/photo-1613844237701-8f3664fc2eff?w=600&q=80",
  },
  {
    id: 2,
    name: "카페 라자냐",
    nameEn: "Cafe Lasagna",
    desc: "리스카페 시그니처 메뉴. 층층이 쌓아 올린 미트 라자냐, 넉넉한 한 접시.",
    price: "₩22,000~",
    priceRange: "메인",
    tag: "Signature",
    image: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80",
  },
  {
    id: 3,
    name: "쉬림프 보드카 마카로니",
    nameEn: "Shrimp Vodka Macaroni",
    desc: "탱글한 새우와 상큼한 보드카 로제 소스. 리뷰어들이 가장 자주 재주문하는 메뉴.",
    price: "₩24,900",
    priceRange: "메인",
    tag: "Popular",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&q=80",
  },
  {
    id: 4,
    name: "미트볼 & 갈릭 라이스",
    nameEn: "Meatball & Garlic Rice",
    desc: "안에서 치즈가 흘러나오는 수제 미트볼. 갈릭 라이스와 함께.",
    price: "₩22,000~",
    priceRange: "메인",
    tag: "",
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600&q=80",
  },
  {
    id: 5,
    name: "샌프란 스타일 갈릭 누들",
    nameEn: "San Francisco Garlic Noodles",
    desc: "해장을 부르는 얼큰한 육수에 쫄깃한 오징어가 올라간 갈릭 누들.",
    price: "₩22,000~",
    priceRange: "메인",
    tag: "",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
  },
  {
    id: 6,
    name: "멕시칸 타코볼 샐러드",
    nameEn: "Mexican Taco Bowl Salad",
    desc: "재료가 넘칠 정도로 가득 담긴 타코볼. 상큼하고 안느끼한 쉬림프 타코 느낌.",
    price: "₩22,000~",
    priceRange: "브런치",
    tag: "Must",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
  },
];

export const locations = [
  {
    id: "pangyo",
    name: "판교점",
    badge: "본점",
    color: "burgundy" as const,
    desc: "백현동 카페거리, 리스카페가 시작된 곳",
    address: "경기 성남시 분당구 판교역로2번길 29 1층",
    addressShort: "판교역로2번길 29",
    hours: "수~일 11:00 – 16:00",
    hoursNote: "월·화 정기 휴무",
    parking: "백현동 공영주차장 이용",
    phone: "",
    naverUrl: "https://map.naver.com/p/search/리스카페 판교",
    features: ["테라스 좌석", "현장 웨이팅"],
  },
  {
    id: "jeongja",
    name: "정자점",
    badge: "",
    color: "forest" as const,
    desc: "정자역 도보 2분, 파라곤 건물",
    address: "경기 성남시 분당구 정자일로 210 120호",
    addressShort: "정자일로 210 120호",
    hours: "매일 10:00 – 20:00",
    hoursNote: "라스트오더 19:00",
    parking: "동양 정자 파라곤 아파트 지하주차장",
    phone: "",
    naverUrl: "https://map.naver.com/p/search/리스카페 정자",
    features: ["연중무휴", "2시간 주차 지원"],
  },
  {
    id: "yeouido",
    name: "여의도점",
    badge: "New",
    color: "burgundy" as const,
    desc: "브라이튼 여의도 1층, 더현대서울 맞은편",
    address: "서울 영등포구 국제금융로 39 판매시설동 1층 124~5호",
    addressShort: "국제금융로 39 판매시설동 1층",
    hours: "매일 10:00 – 21:15",
    hoursNote: "라스트오더 20:30 / 브레이크타임 없음",
    parking: "브라이튼 여의도 지하주차장 (4만원 이상 1시간, 7만원 이상 2시간)",
    phone: "0507-1455-6337",
    naverUrl: "https://map.naver.com/p/search/리스카페 여의도",
    features: ["연중무휴", "테이블링 현장대기"],
  },
];

export const waitingTips = [
  { icon: "clock", tip: "오전 11시 이전 일찍 오면 웨이팅이 짧습니다." },
  { icon: "users", tip: "2인 방문 시 바 자리를 이용하면 대기 없이 입장 가능한 경우가 많아요." },
  { icon: "clock-3", tip: "오후 12시 30분 이후에는 점심 회전이 끝나 한적해지는 경우가 많습니다." },
  { icon: "utensils", tip: "1인 1메뉴 주문이 기본이며, 메뉴당 양이 상당히 많습니다." },
];

export const spaceFeatures = [
  { icon: "music", title: "올드 팝 플레이리스트", desc: "매장 분위기와 어울리는 빈티지 팝·재즈" },
  { icon: "sun", title: "브런치 타임", desc: "햇살 좋은 낮, 여유로운 브런치 한 끼" },
  { icon: "gem", title: "공간 디테일", desc: "미국 레스토랑 감성의 세심한 소품 구성" },
  { icon: "sparkles", title: "저녁 디너", desc: "따뜻한 조명 아래 편안한 디너 타임" },
];
